In [1]:
from snapvx import *
import time
import numpy as np

In [2]:
#Create new graph
gvx = TGraphVX()

#Use CVXPY syntax to define a problem
x1 = Variable(1, name='x1')
obj = square(x1)
#Add Node 1 with the given objective, with the constraint that x1 <= 10
gvx.AddNode(1, Objective=obj, Constraints=[x1 <= 10])

#Similarly, add Node 2 with objective |x2 + 3|
x2 = Variable(1, name='x2')
obj2 = abs(x2 + 3)
gvx.AddNode(2, obj2, [])

#Add an edge between the two nodes, 
#Define an objective, constraints using CVXPY syntax
gvx.AddEdge(1, 2, Objective=square(norm(x1 - x2)), Constraints=[])


-1

In [3]:
#Solve the problem, and print the solution
gvx.Solve()
print gvx.PrintSolution()

Status: Optimal
Total Objective: 2.500335
Node 1:
  x1 [-0.51706729]
Node 2:
  x2 [-1.02366535]
None


In [22]:
def laplace_reg(src, dst, data):
    return (e_pen*sum_squares(src['x'] - dst['x']), [])

In [47]:
def train_loss_calculator(gvx,num_nodes, x_dimension, train_per_node):
    
    train_loss = 0
    # T1
    for i in range(num_nodes):
        if i <= 2:
            x = gvx.GetNodeValue(i+1,'x')
            for k in range(train_per_node):
                w =  w1[i*train_per_node+k] 
                noise = noise1[i*train_per_node+k]
    #             w = np.random.normal(0, 1, 50)
    #             noise = np.random.normal(0, 0.1, 1)
                y =  np.dot(a1[:x_dimension], w) + a1[x_dimension] + noise
                #print(y)
                pred_y = np.dot(x[:x_dimension], w) + x[x_dimension]
                train_loss += square(pred_y - y)

        else:
            x = gvx.GetNodeValue(i+1,'x')

            for k in range(train_per_node):
                w =  w1[i*train_per_node+k] 
                noise = noise1[i*train_per_node+k]
    #             w = np.random.normal(0, 1, 50)
    #             noise = np.random.normal(0, 0.1, 1)
                y =  np.dot(a2[:x_dimension], w) + a2[x_dimension] + noise
                pred_y = np.dot(x[:x_dimension], w) + x[x_dimension]
                train_loss += square(pred_y - y)
    # T2            
    for i in range(num_nodes):
        if i < 2:
            x = gvx.GetNodeValue(5+i+1,'x')

            for k in range(train_per_node):
                w =  w2[i*train_per_node+k] 
                noise = noise2[i*train_per_node+k]
    #             w = np.random.normal(0, 1, 50)
    #             noise = np.random.normal(0, 0.1, 1)
                y =  np.dot(a1_2[:x_dimension], w) + a1_2[x_dimension] + noise
                pred_y = np.dot(x[:x_dimension], w) + x[x_dimension]
                train_loss += square(pred_y - y)

        else:
            x = gvx.GetNodeValue(5+i+1,'x')

            for k in range(train_per_node):
                w =  w2[i*train_per_node+k] 
                noise = noise2[i*train_per_node+k]
    #             w = np.random.normal(0, 1, 50)
    #             noise = np.random.normal(0, 0.1, 1)
                y =  np.dot(a2_2[:x_dimension], w) + a2_2[x_dimension] + noise
                pred_y = np.dot(x[:x_dimension], w) + x[x_dimension]
                train_loss += square(pred_y - y)
    # T3            
    for i in range(num_nodes):
        if i <= 2:
            x = gvx.GetNodeValue(10+i+1,'x')

            for k in range(train_per_node):
                w =  w3[i*train_per_node+k] 
                noise =  noise3[i*train_per_node+k]
    #             w = np.random.normal(0, 1, 50)
    #             noise = np.random.normal(0, 0.1, 1)
                y =  np.dot(a1_3[:x_dimension], w) + a1_3[x_dimension] + noise
                pred_y = np.dot(x[:x_dimension], w) + x[x_dimension]
                train_loss += square(pred_y - y)

        else:
            x = gvx.GetNodeValue(10+i+1,'x')

            for k in range(train_per_node):
                w =  w3[i*train_per_node+k] 
                noise =  noise3[i*train_per_node+k]
    #             w = np.random.normal(0, 1, 50)
    #             noise = np.random.normal(0, 0.1, 1)
                y =  np.dot(a2_3[:x_dimension], w) + a2_3[x_dimension] + noise
                pred_y = np.dot(x[:x_dimension], w) + x[x_dimension]
                train_loss += square(pred_y - y)

    print('Train Loss: ' , train_loss.value)

In [88]:
# Test performance via total loss on random test set
def test_loss_calculator(gvx,num_nodes, x_dimension, test_per_node):
    test_loss = 0
    #np.random.seed(2)
    np.random.seed(3)
    cos_sim_t1 = 0
    cos_sim_t2 = 0
    cos_sim_t3 = 0
    # T1
    for i in range(num_nodes):
        if i <= 2:
            x = gvx.GetNodeValue(i+1,'x')
            cos_sim_t1 += np.dot(x,a1) / (sqrt(sum([a*a for a in x]))*sqrt(sum([a*a for a in a1])))
            for k in range(test_per_node):
                w = np.random.normal(0, 1, n-1)
                noise = np.random.normal(0, reg_noise, 1)
                y =  np.dot(a1[:x_dimension], w) + a1[x_dimension]
                #print(y)
                pred_y = np.dot(x[:x_dimension], w) + x[x_dimension]
                test_loss += square(pred_y - y)

        else:
            x = gvx.GetNodeValue(i+1,'x')
            cos_sim_t1 += np.dot(x,a2) / (sqrt(sum([a*a for a in x]))*sqrt(sum([a*a for a in a2])))
            for k in range(test_per_node):
                w = np.random.normal(0, 1, n-1)
                noise = np.random.normal(0, reg_noise, 1)
                y =  np.dot(a2[:x_dimension], w) + a2[x_dimension]
                pred_y = np.dot(x[:x_dimension], w) + x[x_dimension]
                test_loss += square(pred_y - y)
    # T2            
    for i in range(num_nodes):
        if i < 2:
            x = gvx.GetNodeValue(5+i+1,'x')
            cos_sim_t2 += np.dot(x,a1_2) / (sqrt(sum([a*a for a in x]))*sqrt(sum([a*a for a in a1_2])))
            for k in range(test_per_node):
                w = np.random.normal(0, 1, n-1)
                noise = np.random.normal(0, reg_noise, 1)
                y =  np.dot(a1_2[:x_dimension], w) + a1_2[x_dimension]
                pred_y = np.dot(x[:x_dimension], w) + x[x_dimension]
                test_loss += square(pred_y - y)

        else:
            x = gvx.GetNodeValue(5+i+1,'x')
            cos_sim_t2 += np.dot(x,a2_2) / (sqrt(sum([a*a for a in x]))*sqrt(sum([a*a for a in a2_2])))
            for k in range(test_per_node):
                w = np.random.normal(0, 1, n-1)
                noise = np.random.normal(0, reg_noise, 1)
                y =  np.dot(a2_2[:x_dimension], w) + a2_2[x_dimension]
                pred_y = np.dot(x[:x_dimension], w) + x[x_dimension]
                test_loss += square(pred_y - y)
    # T3            
    for i in range(num_nodes):
        if i <= 2:
            x = gvx.GetNodeValue(10+i+1,'x')
            cos_sim_t3 += np.dot(x,a1_3) / (sqrt(sum([a*a for a in x]))*sqrt(sum([a*a for a in a1_3])))
            for k in range(test_per_node):
                w = np.random.normal(0, 1, n-1)
                noise = np.random.normal(0, reg_noise, 1)
                y =  np.dot(a1_3[:x_dimension], w) + a1_3[x_dimension]
                pred_y = np.dot(x[:x_dimension], w) + x[x_dimension]
                test_loss += square(pred_y - y)

        else:
            x = gvx.GetNodeValue(10+i+1,'x')
            cos_sim_t3 += np.dot(x,a2_3) / (sqrt(sum([a*a for a in x]))*sqrt(sum([a*a for a in a2_3])))
            for k in range(test_per_node):
                w = np.random.normal(0, 1, n-1)
                noise = np.random.normal(0, reg_noise, 1)
                y =  np.dot(a2_3[:x_dimension], w) + a2_3[x_dimension]
                pred_y = np.dot(x[:x_dimension], w) + x[x_dimension]
                test_loss += square(pred_y - y)

    print('Test loss', test_loss.value)
    print('Similarities: ', cos_sim_t1.value, cos_sim_t2.value, cos_sim_t3.value)

In [5]:
w1 = []
noise1 = []
w2 = []
noise2 = []
w3 = []
noise3 = []

n = 10
a1 = np.random.normal(0, 1, n)
a2 = np.random.normal(0, 1, n)
a1_2 = a1 + np.random.normal(0, 0.1, n)
a2_2 = a2 + np.random.normal(0, 0.1, n)
a1_3 = a1_2 + np.random.normal(0, 0.1, n)
a2_3 = a2_2 + np.random.normal(0, 0.1, n)

In [128]:
# PARAMETERS 
saved_variables = True
if saved_variables == False:
    w1 = []
    noise1 = []
    w2 = []
    noise2 = []
    w3 = []
    noise3 = []
    
np.random.seed(2)

num_nodes = 5
num_edges = 5

cons = []

total_steps = 5

x_dimension = 9 # Actually this means dimension is 10 (0-9)
n = 10
train_per_node = 10
test_per_node = 20
reg_noise = 0.1

u_reg = 0.01
e_pen = 0.02
e_lambda = 0.2
lambda_1 = 0.2
lambda_2 = 0
lambda_3 = 0.1

m = 2*5 # For beta (# of beta variables)

optimizer()

('Step :', 0, ' ***')
('Solution: ', 11.06637060009453)
('F(x)value: ', 3.0379711707928694)
('Static edge penalties: ', 1.7476149515625945, 87.380747578129728)
('Temporal edge penalties: ', 6.2807844777390658, 31.403922388695328)
('Train Loss: ', 1.9155730296498332)
('Total Beta loss: ', 1.2764275344565723)
('Beta term 1: ', 0.38656309083409263, 1.932815454170463)
('Beta term 2: ', 0.0, nan)
('Beta term 3:', 2.0572462808178118, 20.572462808178116)
('Test loss', 105.98508452947904)
('Similarities: ', 4.9673173045592129, 4.8646764000706728, 4.9119021176704152)
('**** End of step ', 0, ' ****')
('Step :', 1, ' ***')


/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:300: RuntimeWarning: invalid value encountered in double_scalars


('Solution: ', 4.543718031707868)
('F(x)value: ', 1.8247534837990618)
('Static edge penalties: ', 1.8413108479090476, 92.065542395452383)
('Temporal edge penalties: ', 0.87765369999975795, 4.3882684999987891)
('Train Loss: ', 0.6911729498389614)
('Total Beta loss: ', 1.6160633875796928)
('Beta term 1: ', 0.48649130560325171, 2.4324565280162584)
('Beta term 2: ', 0.0, nan)
('Beta term 3:', 2.6956451695345551, 26.95645169534555)
('Test loss', 74.18218466607556)
('Similarities: ', 4.9649712689809409, 4.9389880994957647, 4.9356977301066305)
('**** End of step ', 1, ' ****')
('Step :', 2, ' ***')
('Solution: ', 4.129757066495905)
('F(x)value: ', 1.6672130745360834)
('Static edge penalties: ', 1.8710226943553998, 93.551134717769983)
('Temporal edge penalties: ', 0.59152129760442207, 2.95760648802211)
('Train Loss: ', 0.5337705440281627)
('Total Beta loss: ', 1.7032603263342638)
('Beta term 1: ', 0.51177540406273503, 2.558877020313675)
('Beta term 2: ', 0.0, nan)
('Beta term 3:', 2.8710080548

In [114]:
# Static Example

def optimizer():
    
    for step in range(total_steps):

        gvx = TGraphVX()
        # T1
        #For each node, add an objective
        for i in range(num_nodes):
            if i <= 2:
                x = Variable(n,name='x')
                obj = 0 
                for k in range(train_per_node):
                    if saved_variables:
                        w = w1[i*train_per_node+k] #np.random.normal(0, 1, 50) #
                        #w1.append(w)
                        noise = noise1[i*train_per_node+k] #np.random.normal(0, 0.1, 1) #
                        #noise1.append(noise)
                    else:
                        w = np.random.normal(0, 1, n-1) #w1[i*25+k] #
                        w1.append(w)
                        noise = np.random.normal(0, reg_noise, 1) #noise1[i*25+k] #
                        noise1.append(noise)

                    y =  (np.dot(a1[:x_dimension], w) + a1[x_dimension] + noise)#[0]
                    pred_y = 0
                    for l in range(x_dimension):
                        pred_y += x[l]*w[l]
                    pred_y += x[x_dimension]
                    obj += square(pred_y - y)

        #         cons = [-1 <= val for val in x]
        #         cons = cons + [1 >= val for val in x]
                obj += u_reg*sum_squares(x[:x_dimension])
                gvx.AddNode(i+1, obj, cons) 
            else:
                x = Variable(n,name='x')
                obj = 0 
                for k in range(train_per_node):
                    if saved_variables:
                        w = w1[i*train_per_node+k] #np.random.normal(0, 1, 50) #
                        #w1.append(w)
                        noise =  noise1[i*train_per_node+k]#np.random.normal(0, 0.1, 1) #
                        #noise1.append(noise)
                    else:
                        w = np.random.normal(0, 1, n-1) #w1[i*25+k] #
                        w1.append(w)
                        noise =  np.random.normal(0, reg_noise, 1) #noise1[i*25+k]#
                        noise1.append(noise)

                    y =  (np.dot(a2[:x_dimension], w) + a2[x_dimension] + noise)#[0]
                    pred_y = 0
                    for l in range(x_dimension):
                        pred_y += x[l]*w[l]
                    pred_y += x[x_dimension]
                    obj += square(pred_y - y)

        #         cons = [-1 <= val for val in x]
        #         cons = cons + [1 >= val for val in x]
                obj += u_reg*sum_squares(x[:x_dimension])
                gvx.AddNode(i+1, obj, cons) 
        gvx.AddEdge(1,2)
        gvx.AddEdge(1,3)
        gvx.AddEdge(2,3)
        gvx.AddEdge(3,4)
        gvx.AddEdge(4,5)

        # T2
        #For each node, add an objective
        for i in range(num_nodes):
            if i < 2:
                x = Variable(n,name='x')
                obj = 0 
                for k in range(train_per_node):
                    if saved_variables:
                        w =  w2[i*train_per_node+k] #np.random.normal(0, 1, 50) #
                        #w2.append(w)
                        noise = noise2[i*train_per_node+k] #np.random.normal(0, 0.1, 1)#
                        #noise2.append(noise)
                    else:
                        w = np.random.normal(0, 1, n-1) # w2[i*25+k] #
                        w2.append(w)
                        noise = np.random.normal(0, reg_noise, 1) #noise2[i*25+k] #
                        noise2.append(noise)

                    y =  (np.dot(a1_2[:x_dimension], w) + a1_2[x_dimension] + noise)#[0]
                    pred_y = 0
                    for l in range(x_dimension):
                        pred_y += x[l]*w[l]
                    pred_y += x[x_dimension]
                    obj += square(pred_y - y)

        #         cons = [-1 <= val for val in x]
        #         cons = cons + [1 >= val for val in x]
                obj += u_reg*sum_squares(x[:x_dimension])
                gvx.AddNode(5+i+1, obj, cons) 
            else:
                x = Variable(n,name='x')
                obj = 0 
                for k in range(train_per_node):
                    if saved_variables:
                        w =  w2[i*train_per_node+k] #np.random.normal(0, 1, 50) #
                        #w2.append(w)
                        noise =  noise2[i*train_per_node+k] #np.random.normal(0, 0.1, 1) #
                        #noise2.append(noise)
                    else:
                        w =  np.random.normal(0, 1, n-1) #w2[i*25+k] #
                        w2.append(w)
                        noise =  np.random.normal(0, reg_noise, 1) #noise2[i*25+k] #
                        noise2.append(noise)

                    y =  (np.dot(a2_2[:x_dimension], w) + a2_2[x_dimension] + noise)#[0]
                    pred_y = 0
                    for l in range(x_dimension):
                        pred_y += x[l]*w[l]
                    pred_y += x[x_dimension]
                    obj += square(pred_y - y)

        #         cons = [-1 <= val for val in x]
        #         cons = cons + [1 >= val for val in x]
                obj += u_reg*sum_squares(x[:x_dimension])
                gvx.AddNode(5+i+1, obj, cons) 
        gvx.AddEdge(6,7)
        gvx.AddEdge(6,8)
        gvx.AddEdge(7,8)
        gvx.AddEdge(8,9)
        gvx.AddEdge(9,10)

        #T3
        #For each node, add an objective
        for i in range(num_nodes):
            if i <= 2:
                x = Variable(n,name='x')
                obj = 0 
                for k in range(train_per_node):
                    if saved_variables:
                        w =  w3[i*train_per_node+k] #np.random.normal(0, 1, 50) #
                        #w3.append(w)
                        noise = noise3[i*train_per_node+k] # np.random.normal(0, 0.1, 1) # 
                        #noise3.append(noise)
                    else:
                        w =  np.random.normal(0, 1, n-1) #w3[i*25+k] #
                        w3.append(w)
                        noise =  np.random.normal(0, reg_noise, 1) # noise3[i*25+k] #
                        noise3.append(noise)

                    y =  (np.dot(a1_3[:x_dimension], w) + a1_3[x_dimension] + noise)#[0]
                    pred_y = 0
                    for l in range(x_dimension):
                        pred_y += x[l]*w[l]
                    pred_y += x[x_dimension]
                    obj += square(pred_y - y)

        #         cons = [-1 <= val for val in x]
        #         cons = cons + [1 >= val for val in x]
                obj += u_reg*sum_squares(x[:x_dimension])
                gvx.AddNode(10+i+1, obj, cons) 
            else:
                x = Variable(n,name='x')
                obj = 0 
                for k in range(train_per_node):
                    if saved_variables:
                        w =  w3[i*train_per_node+k] #np.random.normal(0, 1, 50) #
                        #w3.append(w)
                        noise =  noise3[i*train_per_node+k] #np.random.normal(0, 0.1, 1) #
                        #noise3.append(noise)
                    else:
                        w =  np.random.normal(0, 1, n-1) #w3[i*25+k] #
                        w3.append(w)
                        noise =  np.random.normal(0, reg_noise, 1) #noise3[i*25+k] #
                        noise3.append(noise)

                    y =  (np.dot(a2_3[:x_dimension], w) + a2_3[x_dimension] + noise)#[0]
                    pred_y = 0
                    for l in range(x_dimension):
                        pred_y += x[l]*w[l]
                    pred_y += x[x_dimension]
                    obj += square(pred_y - y)

        #         cons = [-1 <= val for val in x]
        #         cons = cons + [1 >= val for val in x]
                obj += u_reg*sum_squares(x[:x_dimension])
                gvx.AddNode(10+i+1, obj, cons) 
        gvx.AddEdge(11,12)
        gvx.AddEdge(11,13)
        gvx.AddEdge(12,13)
        gvx.AddEdge(13,14)
        gvx.AddEdge(14,15)

        gvx.AddEdgeObjectives(laplace_reg)


        if step == 0:

            gvx.AddEdge(1,6, Objective = e_lambda*sum_squares(gvx.GetNodeVariables(1)['x'] - gvx.GetNodeVariables(6)['x']), Constraints = [])
            gvx.AddEdge(2,7, Objective = e_lambda*sum_squares(gvx.GetNodeVariables(2)['x'] - gvx.GetNodeVariables(7)['x']), Constraints = [])
            gvx.AddEdge(3,8, Objective = e_lambda*sum_squares(gvx.GetNodeVariables(3)['x'] - gvx.GetNodeVariables(8)['x']), Constraints = [])
            gvx.AddEdge(4,9, Objective = e_lambda*sum_squares(gvx.GetNodeVariables(4)['x'] - gvx.GetNodeVariables(9)['x']), Constraints = [])
            gvx.AddEdge(5,10, Objective = e_lambda*sum_squares(gvx.GetNodeVariables(5)['x'] - gvx.GetNodeVariables(10)['x']), Constraints = [])
            gvx.AddEdge(6,11, Objective = e_lambda*sum_squares(gvx.GetNodeVariables(6)['x'] - gvx.GetNodeVariables(11)['x']), Constraints = [])
            gvx.AddEdge(7,12, Objective = e_lambda*sum_squares(gvx.GetNodeVariables(7)['x'] - gvx.GetNodeVariables(12)['x']), Constraints = [])
            gvx.AddEdge(8,13, Objective = e_lambda*sum_squares(gvx.GetNodeVariables(8)['x'] - gvx.GetNodeVariables(13)['x']), Constraints = [])
            gvx.AddEdge(9,14, Objective = e_lambda*sum_squares(gvx.GetNodeVariables(9)['x'] - gvx.GetNodeVariables(14)['x']), Constraints = [])
            gvx.AddEdge(10,15, Objective = e_lambda*sum_squares(gvx.GetNodeVariables(10)['x'] - gvx.GetNodeVariables(15)['x']), Constraints = [])

        else:
            gvx.AddEdge(1,6, Objective = e_lambda*sum_squares(Betas.value[:,0] + gvx.GetNodeVariables(1)['x'] - gvx.GetNodeVariables(6)['x']), Constraints = [])
            gvx.AddEdge(2,7, Objective = e_lambda*sum_squares(Betas.value[:,1] + gvx.GetNodeVariables(2)['x'] - gvx.GetNodeVariables(7)['x']), Constraints = [])
            gvx.AddEdge(3,8, Objective = e_lambda*sum_squares(Betas.value[:,2] + gvx.GetNodeVariables(3)['x'] - gvx.GetNodeVariables(8)['x']), Constraints = [])
            gvx.AddEdge(4,9, Objective = e_lambda*sum_squares(Betas.value[:,3] + gvx.GetNodeVariables(4)['x'] - gvx.GetNodeVariables(9)['x']), Constraints = [])
            gvx.AddEdge(5,10, Objective = e_lambda*sum_squares(Betas.value[:,4] + gvx.GetNodeVariables(5)['x'] - gvx.GetNodeVariables(10)['x']), Constraints = [])
            gvx.AddEdge(6,11, Objective = e_lambda*sum_squares(Betas.value[:,5] + gvx.GetNodeVariables(6)['x'] - gvx.GetNodeVariables(11)['x']), Constraints = [])
            gvx.AddEdge(7,12, Objective = e_lambda*sum_squares(Betas.value[:,6] + gvx.GetNodeVariables(7)['x'] - gvx.GetNodeVariables(12)['x']), Constraints = [])
            gvx.AddEdge(8,13, Objective = e_lambda*sum_squares(Betas.value[:,7] + gvx.GetNodeVariables(8)['x'] - gvx.GetNodeVariables(13)['x']), Constraints = [])
            gvx.AddEdge(9,14, Objective = e_lambda*sum_squares(Betas.value[:,8] + gvx.GetNodeVariables(9)['x'] - gvx.GetNodeVariables(14)['x']), Constraints = [])
            gvx.AddEdge(10,15, Objective = e_lambda*sum_squares(Betas.value[:,9] + gvx.GetNodeVariables(10)['x'] - gvx.GetNodeVariables(15)['x']), Constraints = [])


        # Graph is ready, now solve it!!
        print('Step :', step, ' ***')
        t_0 = time.time()
        gvx.Solve()
        t_1 = time.time()

    #     print('Total time passed: ', str(t_1-t_0))
        print('Solution: ', gvx.value)

        # Split loss into terms

        edge_penalties = 0
        for ei in gvx.Edges():
            src_id = ei.GetSrcNId()
            src_vars = gvx.GetNodeValue(src_id, 'x')
            dst_id = ei.GetDstNId()
            dst_vars = gvx.GetNodeValue(dst_id, 'x')
            edge_diff = src_vars - dst_vars
            edge_penalties += sum([x*x for x in edge_diff])

        B_term_1_T = 0
        B_term_1 = 0
        for i in range(10):
            penalties_B_X = gvx.GetNodeValue(i+1,'x') - gvx.GetNodeValue(i+1+5,'x')
            if step == 0:
                penalties_B_X_T = penalties_B_X
            else:
                penalties_B_X_T = np.squeeze(np.asarray(Betas.value[:,i])) + gvx.GetNodeValue(i+1,'x') - gvx.GetNodeValue(i+1+5,'x')
            B_term_1 += sum([x*x for x in penalties_B_X])
            B_term_1_T += e_lambda*sum([x*x for x in penalties_B_X_T])

        edge_penalties = edge_penalties -  B_term_1   
        print ('F(x)value: ', gvx.value - B_term_1_T - e_pen*edge_penalties)
        print ('Static edge penalties: ', e_pen*edge_penalties, edge_penalties)
        print ('Temporal edge penalties: ', B_term_1_T,  B_term_1_T/e_lambda) 
        train_loss_calculator(gvx, num_nodes, x_dimension, train_per_node)



        # Construct the problem.
        Betas = Variable(n,m)
        total_loss = 0
        for i in range(m):
            total_loss += lambda_1*sum_squares(Betas[:,i] + gvx.GetNodeValue(i+1,'x') - gvx.GetNodeValue(i+1+5,'x')) 
        for i in range(m/2):
            total_loss +=  lambda_2*sum_squares(Betas[:,i] - Betas[:,i+5])
        for i in range(m/2):
            total_loss +=  lambda_3*(sum_squares(Betas[:,i]) + lambda_3*sum_squares(Betas[:,i+5]))  


        objective = Minimize(total_loss)
        constraints = []
        # for i in range(n):
        #     for j in range(m):
        #         constraints = constraints + [-1 <= Betas[i,j], Betas[i,j] <= 1]
        prob = Problem(objective, constraints)

        # The optimal objective is returned by prob.solve().
        result = prob.solve()
        # The optimal value for x is stored in x.value.

        print ('Total Beta loss: ', result)

        # Penalty for each term
        Beta_term_1 = 0
        for i in range(m):
            penalties_B_X = np.squeeze(np.asarray(Betas.value[:,i])) + gvx.GetNodeValue(i+1,'x') - gvx.GetNodeValue(i+1+5,'x')
        #     print('**', gvx.GetNodeValue(i+1,'x').shape)
        #     print('**', type(gvx.GetNodeValue(i+1,'x')))
        #     print('**', np.squeeze(np.asarray(Betas.value[:,i])).shape)

        #     print('**', type(np.squeeze(np.asarray(Betas.value[:,i]))))
        #     print('*****', penalties_B_X.shape)
            Beta_term_1 += lambda_1*sum([x*x for x in penalties_B_X]) 
            #B_term_1 += lambda_1*sum([x*x for x in (Betas.value[:,i] + gvx.GetNodeValue(i+1,'x') - gvx.GetNodeValue(i+1+5,'x'))])
        print('Beta term 1: ', Beta_term_1, Beta_term_1/lambda_1)

        Beta_term_2 = 0
        for i in range(m/2):
            Beta_term_2 += lambda_2*sum([x*x for x in np.squeeze(np.asarray(Betas.value[:,i]))-np.squeeze(np.asarray(Betas.value[:,i+5]))]) 
        print('Beta term 2: ', Beta_term_2, Beta_term_2/lambda_2)

        Beta_term_3 = 0
        for i in range(m/2):
            Beta_term_3 += lambda_3*sum([x*x for x in np.squeeze(np.asarray(Betas.value[:,i]))]) + lambda_3*sum([x*x for x in np.squeeze(np.asarray(Betas.value[:,i+5]))])
        print('Beta term 3:', Beta_term_3, Beta_term_3/lambda_3)

        # TEST RESULTS
        test_loss_calculator(gvx, num_nodes, x_dimension, test_per_node)

        print('**** End of step ', step, ' ****')


In [54]:
print a1
print a1_2
print a1_3

[-1.21934199  1.14876025 -2.02531503  0.51868094 -0.51156381  0.04516914 -1.39725192 -1.51603688 -0.21488301  0.80664517]
[-1.2615938   1.09137959 -1.93942279  0.40620766 -0.44262555  0.11306742 -1.39024369 -1.59249626 -0.14734546  0.74577395]
[-1.18498659  1.04087914 -1.93869227  0.49726456 -0.36420058  0.05904555 -1.37179706 -1.43416436 -0.06028504  0.72441626]


In [42]:
# t_0 = time.time()
# gvx.Solve()
# t_1 = time.time()
print a1
print a1_2
print a1_3
print a2
print gvx.value
print gvx.PrintSolution()

[-1.21934199  1.14876025 -2.02531503  0.51868094 -0.51156381  0.04516914 -1.39725192 -1.51603688 -0.21488301  0.80664517]
[-0.10206231 -0.40832492  0.56035034  1.23963256  0.4119495  -0.96362254  1.11129942  0.82088491  0.72447633  2.31822846]
0.222248858023
Status: Optimal
Total Objective: 0.222249
Node 1:
  x [-1.35533764  1.10398749 -2.11261016  0.37402481 -0.43526707 -0.13863326 -1.33673326 -1.53994057  0.03014576  0.89174653]
Node 2:
  x [-1.01395101  0.76985598 -1.97011223  0.58996421 -0.32420073  0.34788771 -1.4184618  -1.44984935  0.04749832  0.23489931]
Node 3:
  x [-1.11870559  1.23608127 -2.05796139  0.61791075 -0.49090426  0.26506921 -1.33259232 -1.45780743 -0.18421887  0.96844362]
Node 4:
  x [-0.29519811 -0.65875112  0.38464374  1.11349688  0.64602817 -0.23687129  0.89841013  0.54795337  0.3545761   2.5181651 ]
Node 5:
  x [-0.15900468 -0.51592266  0.53096641  1.43096258  0.58874562 -1.05550622  1.12538348  0.67213039  0.66821881  2.0782236 ]
Node 6:
  x [-1.224108    1.3

In [110]:
regression_penalties = 0
## ToDo -- Penalty check

edge_penalties = 0
for ei in gvx.Edges():
    src_id = ei.GetSrcNId()
    src_vars = gvx.GetNodeValue(src_id, 'x')
    dst_id = ei.GetDstNId()
    dst_vars = gvx.GetNodeValue(dst_id, 'x')
    edge_diff = src_vars - dst_vars
    #if abs(src_id - dst_id) != 5:  
         
    edge_penalties += sum([x*x for x in edge_diff])

B_term_1_T = 0
B_term_1 = 0
for i in range(10):
    penalties_B_X = gvx.GetNodeValue(i+1,'x') - gvx.GetNodeValue(i+1+5,'x')
    penalties_B_X_T = np.squeeze(np.asarray(Betas.value[:,i])) + gvx.GetNodeValue(i+1,'x') - gvx.GetNodeValue(i+1+5,'x')
    B_term_1 += sum([x*x for x in penalties_B_X])
    B_term_1_T += r2*sum([x*x for x in penalties_B_X_T])
    
edge_penalties = edge_penalties -  B_term_1   
print ('F(x)value: ', gvx.value - B_term_1_T - edge_penalties)
print ('Edge penalties: ', edge_penalties)
print ('Temporal edge penalties: ', B_term_1_T ) 

('F(x)value: ', 70.012817462153635)
('Edge penalties: ', 241.97030450680597)
('Temporal edge penalties: ', 147.04330625792039)


In [99]:
#5.0407725617 ---- 1st
#5.62140839552 --- 2nd
#5.68026627551 --- 3rd
#5.68204513814 --- 4th
#5.68023002292 --- 5th



# Beta update 
from cvxpy import *

m = 2*5
lambda_1 = 5
lambda_2 = 5
lambda_3 = 20

# Construct the problem.
Betas = Variable(n,m)
total_loss = 0
for i in range(m):
    total_loss += lambda_1*sum_squares(Betas[:,i] + gvx.GetNodeValue(i+1,'x') - gvx.GetNodeValue(i+1+5,'x')) 
for i in range(m/2):
    total_loss +=  lambda_2*sum_squares(Betas[:,i] - Betas[:,i+5])
for i in range(m/2):
    total_loss +=  lambda_3*(sum_squares(Betas[:,i]) + lambda_3*sum_squares(Betas[:,i+5]))  
    
    
objective = Minimize(total_loss)
constraints = []
# for i in range(n):
#     for j in range(m):
#         constraints = constraints + [-1 <= Betas[i,j], Betas[i,j] <= 1]
prob = Problem(objective, constraints)

# The optimal objective is returned by prob.solve().
result = prob.solve()
# The optimal value for x is stored in x.value.
print Betas.value
print result

# Penalty for each term
B_term_1 = 0
for i in range(m):
    penalties_B_X = np.squeeze(np.asarray(Betas.value[:,i])) + gvx.GetNodeValue(i+1,'x') - gvx.GetNodeValue(i+1+5,'x')
#     print('**', gvx.GetNodeValue(i+1,'x').shape)
#     print('**', type(gvx.GetNodeValue(i+1,'x')))
#     print('**', np.squeeze(np.asarray(Betas.value[:,i])).shape)
    
#     print('**', type(np.squeeze(np.asarray(Betas.value[:,i]))))
#     print('*****', penalties_B_X.shape)
    B_term_1 += lambda_1*sum([x*x for x in penalties_B_X]) 
    #B_term_1 += lambda_1*sum([x*x for x in (Betas.value[:,i] + gvx.GetNodeValue(i+1,'x') - gvx.GetNodeValue(i+1+5,'x'))])
print B_term_1, B_term_1/lambda_1

B_term_2 = 0
for i in range(m/2):
    B_term_2 += lambda_2*sum([x*x for x in np.squeeze(np.asarray(Betas.value[:,i]))-np.squeeze(np.asarray(Betas.value[:,i+5]))]) 
print B_term_2, B_term_2/lambda_2

B_term_3 = 0
for i in range(m/2):
    B_term_3 += lambda_3*sum([x*x for x in np.squeeze(np.asarray(Betas.value[:,i]))]) + lambda_3*sum([x*x for x in np.squeeze(np.asarray(Betas.value[:,i+5]))])
print B_term_3, B_term_3/lambda_3


# for i in range(m-1):
#     print sum_squares(Betas.value[i] + gvx.GetNodeValue(i+1,'x') - gvx.GetNodeValue(i+1+5,'x'))

[[  2.26295542e-02   1.98918738e-02   4.34248306e-02  -1.69415127e-02  -3.09680885e-03  -1.75771153e-03   2.45820347e-04  -2.03281413e-03  -8.27223807e-04  -6.51555690e-04]
 [ -1.49277434e-02  -2.56448828e-02  -1.16713467e-01  -3.89392440e-02  -9.98736682e-03   5.29623471e-04  -1.04976861e-03   2.17950503e-03   1.07126462e-03  -5.63831621e-04]
 [  3.88460261e-02  -2.41815095e-02   3.59910066e-02  -1.66907654e-02   1.41720409e-02   1.57744440e-03   2.27466047e-04   1.44049726e-03  -1.94549499e-03   2.78610388e-04]
 [  1.92377786e-02  -3.65448141e-03   8.53660627e-02  -2.68074766e-02  -6.72575706e-03  -8.82240119e-04   1.42677633e-03   1.52936714e-03   2.83670828e-03  -3.99173723e-04]
 [ -4.40583286e-02  -6.94035434e-03  -1.42379573e-02   3.35978697e-03  -1.74482095e-02   6.27975647e-04  -1.17736987e-03   9.55846824e-05  -3.56697910e-04  -1.49628733e-03]
 [  1.76889609e-02  -1.89912208e-02  -6.35886781e-02  -1.10165317e-02   2.05750522e-03  -1.02106073e-03  -1.32529198e-04  -2.63139821e-

In [ ]:
('Test loss', 1597.1589044734537)
(4.6390697191558994, 4.5192505319485665, 4.6468855885800799)


1070.81680168
(4.6112358988745248, 4.4627492857107658, 4.6045172994488848)

1070.5091783
(4.6113762295512988, 4.4627710941571834, 4.6046484242617085)

1126.44861123
(4.6113762295512988, 4.4627710941571834, 4.6046484242617085)

1116.62563086
(4.6169247325836524, 4.4637415227009818, 4.6098673764359601)

1089.63456755
(4.629792461749247, 4.4674968042281584, 4.6222263455145631)

971.393364363
(4.6738540920039915, 4.4825248898792323, 4.6683964955719235)

## OLD
1125.79594642
(4.6117961200353648, 4.4627982948685299, 4.6050293987880382)



#After fixing matrices into w1,2,3 

1962.66171305
(4.4530182454240963, 4.3606203893919417, 4.5481922347812347)

738.768400796
(4.8115068166077952, 4.7171492479275221, 4.820396509247038)

# Before fixing matrices (This only makes difference when we compute 3 time-stamps seperately)
1-None reg losses
    564.581292151
    664.937592784
    633.651325366
    
2396.97950807
(4.5032426481896266, 4.2483433083711679, 4.5010646180521636)

1-1 reg losses
681.904237346
(4.8509831274086652, 4.7536483914568501, 4.8078107786076938)

1-2 reg losses
605.136647142
(4.8617645377740972, 4.7683566754155873, 4.8292656134070828)

1-5 reg losses
583.3718383
(4.8511840764512231, 4.7567723302765241, 4.8295890235273813)

1-10 reg losses
617.937627281
(4.833551277367877, 4.7392154973538547, 4.817418998869897)

1-20 reg losses
676.817453536
(4.8147970926407293, 4.7148278275907352, 4.8009750561378004)

1-50 reg losses
758.443589006
(4.7950783052833623, 4.6859704146739647, 4.7820063925131961)

1-100 reg losses
804.63887356
(4.7858791086269967, 4.6711083189084519, 4.7726741002856636)

1-1000 reg losses
862.128245312
(4.7756824176180039, 4.6536593532870043, 4.7620667971216664)

1-1000000 reg losses
873.406994009
(4.7739094931355179, 4.6503579147692902, 4.7601167319753817)

In [333]:
np.random.seed(123)
rnd1 = np.random.normal(0, 5, 2)
print(rnd1)
rnd2 = np.random.normal(0, 5, 2)
print(rnd2)
rnd3 = np.random.normal(0, 5, 2)
print(rnd3)
rnd4 = np.random.normal(0, 5, 2)
print(rnd4)

[-5.42815302  4.98672723]
[ 1.41489249 -7.53147357]
[-2.89300126  8.25718269]
[-12.13339622  -2.14456314]


In [335]:
np.random.seed(123)
rnd2 = np.random.normal(0, 5, 2)
print(rnd2)
rnd4 = np.random.normal(0, 5, 2)
print(rnd4)

[-5.42815302  4.98672723]
[ 1.41489249 -7.53147357]
